on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Build
        run: ./build.sh

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 896a5680c83c97d3d9c7987e3dbef09d
          projectName: maze-collections
          directory: build-output
          branch: main

      - name: Git Commit
        run: |
          git config --local user.name "Maze Data Validator & Rating Calculator [bot]"
          git config --local user.email ""
          git add --all
          git commit -m "Maze Data & Rating Update"
          git push origin main